### ISSUE TITLE
MPI gathering

### ISSUE THREAD

**Issue by minhpvo** [Cysu/dgd_person_reid#20]
Thank you for the great work.

I have a question regarding the MPI gathering and boardcasting process.  It seems that the current code gather all the data whenever it does inner product. Yet, I would expect that the gathering to happen during batch norm or the loss layer only. Can you please point me to where I can modify the gathering code?

Thanks,

**Comment by Cysu** [comment]
Currently, it's a hard coded strategy to gather before inner product, in order to prevent reducing the large number of parameters in the FC layers. The related code snippet is around [here](https://github.com/Cysu/caffe/blob/b7472b5d64b90baa69339648cc154e3bd2a42596/src/caffe/net.cpp#L63-L67). However, it would be quite difficult to implement gathering only for BN and loss layers. You may refer to an **untested** synchronized BN implementation [here](https://github.com/yjxiong/caffe/pull/107).

**Comment by minhpvo** [comment]
Thanks for the super prompt reply! I found the places where need to modify.

Yes, it would be hard to implement gathering for BN. 

Regarding the inner product,  beside the computational issues due to its number of parameters, if I remove its gathering step, are there any other dependencies that I need to modify in the code?

**Comment by Cysu** [comment]
I don't think there are any other dependencies. Actually you may set `auto_insert_gathers: false` in prototxt to disable it.

**Comment by minhpvo** [comment]
Thank!
